language: python
python:
- 3.8

before_install:
- openssl aes-256-cbc -K $encrypted_0a8b5c952d03_key -iv $encrypted_0a8b5c952d03_iv -in deploy_scabox.enc -out deploy_scabox -d

install:
- pip install sphinx sphinx_rtd_theme sphinx-argparse recommonmark sphinxext-remoteliteralinclude

scripts:
- echo "Generating documentation..."
- cd docs/sources
- make html
- cd ../build/all/html
- touch .nojekyll
- cd ../../../../

deploy:
  provider: pages:git
  deploy_key: deploy_scabox
  local_dir: docs/build/all/html
  keep_history: true
  edge: true
  on:
    branch: deployement
